[package]
name = "kyopuro-template"
version = "0.1.0"
authors = ["quietsato <quietsato@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
proconio = "0.4.1"
